### ISSUE TITLE
State machine for friendship status.

### ISSUE THREAD

**Issue by sungwoncho** [sungwoncho/has_friendship#13]
A friendship record has many possible values for `status`. Perhaps a state machine will reduce unexpected behaviors in the long run.

**Comment by Pensarfeo** [comment]
Could you comment this. I am not a computer science major.
I understand the concept but what kind of implementation do you imagine?
Cheers

**Comment by sungwoncho** [comment]
Currently we manually update the status of the friendship whenever an action is taken. e.g. `.update(status: 'accepted')`. I thought it'd be more rigorous to define a set of possible states and transitions and follow them rather than directly updating the status.

**Comment by sungwoncho** [comment]
Implemented by#24
