### ISSUE TITLE
Requester can accept his own friend request

### ISSUE THREAD

**Issue by ricardokrieg** [sungwoncho/has_friendship#16]
```ruby
one.friend_request(other)
one.accept_request(other)
```

**one** should not accept the request he created.

Or is this the expected behavior?

**Comment by Pensarfeo** [comment]
I think that right now we are simply not checking since it is not hard to forbid such action in your controller. But probably this action should not be allowed.

**Comment by sungwoncho** [comment]
It is not an expected behavior. I think this is a sensible suggestion. Please send a PR.

**Comment by d4mk0** [comment]
For now i can just use some validation before accept request
```ruby
if HasFriendship::Friendship.where(status: 'requested', friendable_id: current_user.id, friend_id: requested_user.id).exists?
```
