### ISSUE TITLE
blocked_friends

### ISSUE THREAD

**Issue by T3tr0** [sungwoncho/has_friendship#22]
Hello,

Thanks for the gem, it has been very helpful.

Just a heads-up, ```user.blocked_friends``` spawn an error.

I fixed it by addind ```source: :friend``` in the file lib/has_friendship/friendable.rb to the line (15) defining the call.

**Comment by sungwoncho** [comment]
Could you make a PR with your fix, and a short test? Other users will appreciate it.

**Comment by sungwoncho** [comment]
Fixed by #23. The fix was released in v0.1.3.
