### ISSUE TITLE
Database indexes

### ISSUE THREAD

**Issue by f-anthonioz** [sungwoncho/has_friendship#31]
Was just wondering if database indexes and foreign key constraints were left out for a specific reason ?
If not, I can add those for performance sake.

**Comment by sungwoncho** [comment]
Yes, we should index `friend_id` to improve performance. I must have missed it.

**Comment by chevinbrown** [comment]
@f-anthonioz once #60 is released, I'll add migrations to fix this.

**Comment by chevinbrown** [comment]
This should be resolved!
