### ISSUE TITLE
Don't see value inside friendships tables after use friend_request

### ISSUE THREAD

**Issue by zirexba** [sungwoncho/has_friendship#35]
Hi,

I am trying to use this gem in my simple app and I created controller action and provide and everything goes well but when I trying to check pending_friends I am getting  "#<User::ActiveRecord_Associations_CollectionProxy:0xa690f68>"  

Is my controller action code correct ?

def add_friend
    @user = User.find_by_name(params[:id])
    if @user != current_user
      current_user.friend_request(@user)
      redirect_to root_path
    end
  end

**Comment by zirexba** [comment]
I check the db inside rubymine and now I am seeing two records but still @user.pending_friends only returns "#User::ActiveRecord_Associations_CollectionProxy:0xa690f68"

**Comment by sungwoncho** [comment]
What version are you using?

**Comment by Eblohm** [comment]
This is because @user.pending_friends returns an array of database associations, so you have to loop through them.

`@user.pending_friends.each do |pending_friend|
    pending_friend.username + ' wants to be your friend.
end`

Would display the pending friends for the user

**Comment by sungwoncho** [comment]
@Eblohm I thought we could see all pending friends without looping through an array. See [this test](https://github.com/sungwoncho/has_friendship/blob/2fd83c8688730ba00c179836e1c1c766e040a989/spec/has_friendship/feature_spec.rb#L13).

Am I wrong? Then we might need to update the doc [here](https://github.com/sungwoncho/has_friendship#pending_friends).

**Comment by Eblohm** [comment]
@sungwoncho when I wrote my code (which was on 0.1.3 so it might've changed) I had to loop through it. I haven't looked at it recently because it works but I'll check it when I get home tonight to see if it's an unnecessary loop

**Comment by Eblohm** [comment]
@sungwoncho yeah, pending_friends needs to be looped through. I believe that test is passing because the array does include the user, just not in the desired way.

**Comment by zirexba** [comment]
@Eblohm Yes, it is a list. Thank you!

**Comment by sungwoncho** [comment]
@zirexba was the doc misleading? If so, how can we improve?

**Comment by zirexba** [comment]
Hey @sungwoncho, maybe just  little note beside information about pending_friends that response  information is a list/array. Also, @Eblohm  one suggestion, How about getting date/time  of friendship.
Like "Friends from  12/12/2020".    

Thank you!

**Comment by sungwoncho** [comment]
Can you do a PR for the doc? As for the timestamp, we already have it. See [the schema](https://github.com/sungwoncho/has_friendship/blob/master/spec/internal/db/schema.rb#L22).

**Comment by sungwoncho** [comment]
Hopefully #36 made it clearer in the doc. Closing.
