### ISSUE TITLE
Dont work with rails 5.1.3

### ISSUE THREAD

**Issue by nikolaylositskiy** [sungwoncho/has_friendship#48]
Bundler could not find compatible versions for gem "rails":
  In snapshot (Gemfile.lock):
    rails (= 5.1.3)

  In Gemfile:
    rails (~> 5.1.3)

    has_friendship (~> 1.1) was resolved to 1.1.0, which depends on
      rails (< 5.1.0, >= 4.0.0)

**Comment by Hawry** [comment]
This happened to me too, I forked this repo and modified the .gemspec file to allow rails 5.1 and modified the migration version as well and I'm currently using the fork as the gem source, until the dependency versions is updated in this repo. I haven't discovered any compatibility issues with the changed so far.

**Comment by daniel-g** [comment]
Already fixed in 3dbd72574f2857de9216991704788879587d6fe8

**Comment by chevinbrown** [comment]
This should be corrected in the most current release. 

Please correct me if I’m wrong.
