### ISSUE TITLE
How to check if a user is friends with a specific user?

### ISSUE THREAD

**Issue by jordansinger** [sungwoncho/has_friendship#5]
I'd like to return a boolean in a search query for each user if the current user is friends with that user. Possible with some .includes and .where?

**Comment by sungwoncho** [comment]
I think you can use `HasFriendship.Friendship.exist?(friendable, friend)` The order of the argument is not important. 

See https://github.com/sungwoncho/has_friendship/blob/master/lib/has_friendship/friendship.rb#L8

**Comment by sungwoncho** [comment]
I added an instance method `friends_with?` for Friendables (https://github.com/sungwoncho/has_friendship/pull/6). Upgrade the gem to use it.

**Comment by jordansinger** [comment]
Thanks for creating the method, I have a few questions and potentially an issue as well.

First of all, if I check current_user.friends_with?(user) when they are not friends, it returns false, but when I flip it so that user.friends_with?(current_user) when they are not friends, it returns true, so I think there may be some issue in the logic, because that should return the same value in both scenarios.

Secondly, I'd appreciate if I could get some help on improving a query that's making multiple SELECT queries.

I have the following code:
```
<% User.all.each do |user| %>
	<%= current_user.friends_with?(user) %>
<% end %>
```
This returns the correct friends_with value when it's checking the current_user against an arbitrary user, but like I said above, when flipped (<%= user.friends_with?(current_user) %>), it returns true always. So my question is how can I, if at all possible, avoid querying the friendships table every single iteration and do some sort of .includes or .preload in order to not have to hit the database every iteration.

Thanks Sung!

**Comment by sungwoncho** [comment]
I fixed the `#friends_with?` logic and pushed the patch to `devel` branch.

By the design of your code, I don't think it's possible to dial it down to one query, because it is iterating through every user and calling `#friends_with` on each of them. Maybe you can save a reference to `current_user.friends` collection and check by calling `#include?(user)`.

```ruby
@friends = current_user.friends
...
<% User.all.each do |user| %>
    <%= @friends.include?(user) %>
<% end %>
```

Let me know if you have a better way.
