### ISSUE TITLE
Friendship between two models

### ISSUE THREAD

**Issue by malasaad82** [sungwoncho/has_friendship#52]
Hi,
Is it possible to create friendship between two models, I am not sure if its right but the idea is more like this:
User1 with Manager role will add a POST1
User2 with Coworker role can send a request to join POST1 to be a Team member of POST1.
User1 can send request to let user2 be part of Teams
User1/User2 can approve or reject if they got request.
If anyone removes the relation so it's removed from both.

Any idea or way to do that.
Thanks

**Comment by chevinbrown** [comment]
This is currently out of scope for this gem. The main purpose is to add a polymorphic join between records of one data type.
I will be attempting to clean up the current code to support the basic associations that should exist. However, that can be fairly easily accomplished by a polymorphic group. 😄
