### ISSUE TITLE
Specify the Rails release that migration is for

### ISSUE THREAD

**Issue by pcasa** [sungwoncho/has_friendship#53]
rake db:migrate fails

Nothing huge, but got the error "Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for:"

Easy fix, just add [4.2] to all the migration files such as "class CreateFriendships < ActiveRecord::Migration" to "class CreateFriendships < ActiveRecord::Migration[4.2]".  

Would be nice if generators could check rails version and add this or at least update Readme for others.

Rails: 5.1.4
has_friendship: 1.1.1

**Comment by chevinbrown** [comment]
This should be fixed by #57. 

❤️
