### ISSUE TITLE
A blockee can unblock friend with the blocker

### ISSUE THREAD

**Issue by jiehaoliu** [sungwoncho/has_friendship#62]
Hi there,
First of all I am not sure if this situation is expected, when userA blocks userB, userA will also get blocked by userB.

If it is true, then I just tried something like:
@userA.block_friend(@userB)
@userB.unblock_friend(@userA)

It actually worked and removed userB from userA's blocked list, which should not happen as described in README. 

I am wondering if anybody else has the same issue or just me doing something wrong?

Any answer or clarification is appreciated, thanks!

**Comment by chevinbrown** [comment]
@jiehaoliu I've not had a moment to look at this. 

Did you close because you figured out a solution?

**Comment by jiehaoliu** [comment]
If you can take a look at this issue that would be great.
I am wondering if it is just my db issue thats why I closed it, but I do not have a solution yet.

**Comment by jiehaoliu** [comment]
Here is my assumption:
if the block function intends to mutually blocks blocker & blockee, then I guess it might be reason why a blockee can unblock because he is also a blocker in this case.

**Comment by chevinbrown** [comment]
I'm a new maintainer, so I'm not yet very familiar...but you're correct. The "block" functionality is not very robust right now and this obviously has some loopholes.

**Comment by jiehaoliu** [comment]
Please feel free to ask me If you need more information to investigate the issue, I am a newbie to rails but I will try my best to help. Hope this issue could be solved soon. Cheers!
