### ISSUE TITLE
Doesn't work with rails 6.1

### ISSUE THREAD

**Issue by mices** [sungwoncho/has_friendship#85]
You still haven't added support for activestorage 6.1 which goes together with rails 6.1 so you never added support for rails 6.1

**Comment by chevinbrown** [comment]
Sorry, @mices, this package isn't maintained anymore.

**Comment by mices** [comment]
In Gemfile:
    has_friendship was resolved to 1.1.8, which depends on
      activesupport (>= 4.2.0, < 6.1)

    rails (~> 6.1.0) was resolved to 6.1.4, which depends on
      activesupport (= 6.1.4)

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.

Bundler could not find compatible versions for gem "rails":
  In snapshot (Gemfile.lock):
    rails (= 6.1.4)

  In Gemfile:
    rails (~> 6.1.0)

    has_friendship was resolved to 0.0.3, which depends on
      rails (~> 4.1.8)

**Comment by mices** [comment]
Sorry, I just needed to use the master branch It bundles with rails 6.1.4, so it works
